-- SEED PRODUCTS (FROM mock.js)
-- Jalankan ini di Supabase SQL Editor SETELAH bikin table 'products'

insert into products (kode, nama, image, position) values
  ('D-73-PRS', 'Papersilk with Puring', '/mock/D-73-PRS.webp', 1),
  ('D-69-TUL', 'Tulle x Malaga', '/mock/D-69-TUL.webp', 2),
  ('D-68-TUL', 'Tulle x Malaga', '/mock/D-68-TUL.webp', 3),
  ('D-67-TUL', 'Tulle x Malaga', '/mock/D-67-TUL.webp', 4),
  ('D-66-AUR', 'Aurora x Malaga', '/mock/D-66-AUR.webp', 5),
  ('D-65-AUR', 'Aurora x Malaga', '/mock/D-65-AUR.webp', 6),
  ('D-64-SFN-BW', 'Sifon x Malaga', '/mock/D-64-SFN-BW.webp', 7),
  ('D-64-SFN', 'Sifon x Malaga', '/mock/D-64-SFN.webp', 8),
  ('D-63-SFN', 'Sifon x Malaga', '/mock/D-63-SFN.webp', 9),
  ('D-62-SFN', 'Sifon x Malaga', '/mock/D-62-SFN.webp', 10),
  ('D-61-SFN', 'Sifon x Malaga', '/mock/D-61-SFN.webp', 11),
  ('D-60-AUR', 'Aurora x Jasmine', '/mock/D-60-AUR.webp', 12),
  ('D-59-AUR', 'Aurora x Jasmine', '/mock/D-59-AUR.webp', 13),
  ('D-58-BLD', 'Bella Donna x Jasmine', '/mock/D-58-BLD.webp', 14),
  ('D-57-BLD', 'Bella Donna x Jasmine', '/mock/D-57-BLD.webp', 15),
  ('D-56-AUR', 'Aurora x Jasmine', '/mock/D-56-AUR.webp', 16),
  ('D-55-AUR', 'Aurora x Jasmine', '/mock/D-55-AUR.webp', 17),
  ('D-54-AUR', 'Aurora x Jasmine', '/mock/D-54-AUR.webp', 18),
  ('D-53-GIA', 'Giana x Jasmine', '/mock/D-53-GIA.webp', 19),
  ('D-52-GIA', 'Giana x Jasmine', '/mock/D-52-GIA.webp', 20),
  ('D-51-BLD', 'Bella Donna x Jasmine', '/mock/D-51-BLD.webp', 21),
  ('D-50-BLD', 'Bella Donna x Jasmine', '/mock/D-50-BLD.webp', 22),
  ('D-49-AUR', 'Aurora x Jasmine x Santili', '/mock/D-49-AUR.webp', 23),
  ('D-34-PRS', 'Papersilk x Bordir', '/mock/D-34-PRS.webp', 24),
  ('D-43-SFN', 'Sifon Sutra', '/mock/D-43-SFN.webp', 25),
  ('D-42-SFN', 'Sifon Sutra', '/mock/D-42-SFN.webp', 26),
  ('D-48-AUR', 'Aurora x Jasmine', '/mock/D-48-AUR.webp', 27),
  ('D-47-AUR', 'Aurora x Jasmine', '/mock/D-47-AUR.webp', 28),
  ('D-46-GIA', 'Giana x Jasmine', '/mock/D-46-GIA.webp', 29),
  ('D-45-JP', 'Jacquard Premium x Jasmine', '/mock/D-45-JP.webp', 30),
  ('D-44-JP', 'Jacquard Premium x Jasmine', '/mock/D-44-JP.webp', 31),
  ('D-41-SFN', 'Sifon x Papersilk Twotone', '/mock/D-41-SFN.webp', 32),
  ('D-39-SFN', 'Sifon x Papersilk Twotone', '/mock/D-39-SFN.webp', 33),
  ('D-38-SFN', 'Sifon x Papersilk Twotone', '/mock/D-38-SFN.webp', 34),
  ('D-37-PRD', 'Prada x Jasmine', '/mock/D-37-PRD.webp', 35),
  ('D-36-PRD', 'Prada x Jasmine', '/mock/D-36-PRD.webp', 36),
  ('D-35-PRD', 'Prada x Jasmine', '/mock/D-35-PRD.webp', 37),
  ('D-33-PRS', 'Papersilk x Bordir', '/mock/D-33-PRS.webp', 38),
  ('D-32-PRS', 'Papersilk x Bordir', '/mock/D-32-PRS.webp', 39),
  ('D-31-PRS', 'Papersilk x Bordir', '/mock/D-31-PRS.webp', 40),
  ('D-30-PRS', 'Papersilk x Bordir', '/mock/D-30-PRS.webp', 41),
  ('D-29-PRS', 'Papersilk x Bordir', '/mock/D-29-PRS.webp', 42),
  ('D-28-BLD', 'Belladonna x Jasmine', '/mock/D-28-BLD.webp', 43),
  ('D-27-BLD', 'Jetblack x Jasmine', '/mock/D-27-BLD.webp', 44),
  ('D-26-BLD', 'Jetblack x Jasmine', '/mock/D-26-BLD.webp', 45),
  ('D-25-JB', 'Jetblack x Jasmine', '/mock/D-25-JB.webp', 46),
  ('D-24-JB', 'Jetblack x Jasmine', '/mock/D-24-JB.webp', 47),
  ('D-23-ARM', 'Armani x Jasmine', '/mock/D-23-ARM.webp', 48),
  ('D-20-OSK', 'Osaka x Jasmine', '/mock/D-20-OSK.webp', 49),
  ('D-18-JB', 'Jetblack x Jasmine', '/mock/D-18-JB.webp', 50),
  ('D-17-JB', 'Jetblack x Jasmine', '/mock/D-17-JB.webp', 51),
  ('D-16-JB', 'Jetblack x Jasmine', '/mock/D-16-JB.webp', 52),
  ('D-15-ARM', 'Armani x Jasmine', '/mock/D-15-ARM.webp', 53),
  ('D-14-ARM', 'Armani x Jasmine', '/mock/D-14-ARM.webp', 54),
  ('D-09-OSK', 'Osaka x Jasmine', '/mock/D-09-OSK.webp', 55),
  ('D-08-OSK', 'Osaka x Jasmine', '/mock/D-08-OSK.webp', 56),
  ('D-07-OSK', 'Osaka x Jasmine', '/mock/D-07-OSK.webp', 57),
  ('D-04-OSK', 'Osaka x Jasmine', '/mock/D-04-OSK.webp', 58),
  ('D-03-OSK', 'Osaka x Jasmine', '/mock/D-03-OSK.webp', 59)
on conflict (kode) do nothing;
